name = "Salvage"
author = "TheKingNate"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9067697ce4263cffb78abc9471663ea72ee12fd794b77b22838417995cac78b2"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
datapack-folder = "globalpacks/datapacks"
