name = "Salvage"
author = "TheKingNate"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "024f987cabaf52cfa10a5a2e08f0ea1e2221a7f34b757ad81bac7a4babc003a9"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
datapack-folder = "globalpacks/datapacks"
