name = "Salvage"
author = "TheKingNate"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f10adb7d22cfaf1d3d2ebbfa0182d7e41ce9d176aaefd08dd5afeb18d20f509e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
datapack-folder = "globalpacks/datapacks"
