 ("Quality of Life", "The mods with no items", "minecraft:spyglass", [
  (0, 0, "Look At Anything",
   ["Jade draws a tooltip for whatever block or mob is under your crosshair.", "",
    "It reads tank contents, energy buffers, crop growth and mob health straight",
    "out of the block. Every machine in this cluster reports through it.", "",
    "Controls -> Jade -> Open Config turns individual lines on and off."],
   [t_check("Read a machine's energy buffer off the Jade tooltip")],
   [r_xp(40), r_skill(2)]),
  (2, 0, "Look It Up",
   ["Roughly Enough Items lists every item in the pack down the right edge.", "",
    "Left-click an item for its recipe. RIGHT-click it for what it is used in --",
    "that is the half people forget, and it is how you work forwards.", "",
    "Type @powah to filter by mod, #ingots to filter by tag."],
   [t_check("Find a recipe with REI, then right-click for its uses")],
   [r_xp(40), r_skill(2)]),
  (2, -2, "Fix The Options Screen",
   ["Two small mods that only matter because this pack is huge.", "",
    "Controlling adds a search box to Options -> Controls. Type an action name,",
    "or click the key field and press a key to see everything already bound to it.", "",
    "Mouse Tweaks: hold left-click and sweep across slots to move a row.",
    "Scroll the wheel over a slot to push items to the other container."],
   [t_check("Find a keybind conflict with Controlling's search")],
   [r_xp(40), r_skill(2)]),
  (4, 0, "Read The Hunger Bar",
   ["AppleSkin overlays what a food will restore before you eat it.", "",
    "Ghost drumsticks are hunger. The darker bar behind them is SATURATION,",
    "which is the number that actually decides how long until you are hungry again.", "",
    "Held-item preview also shows on the exhaustion side, so you can see",
    "sprinting and swimming draining you."],
   [t_check("Compare the saturation of two different foods")],
   [r_xp(40), r_skill(2)]),
  (6, 0, "Two Minimaps",
   ["You are running two mapping systems and by default they overlap.", "",
    "Xaero's Minimap and Xaero's World Map are one pair; FTB Chunks ships its",
    "own minimap and full map. Pick one minimap and disable the other.", "",
    "Keep FTB Chunks' map: it is the only one that draws chunk claims."],
   # t_stat("minecraft:walk_one_cm", 300000) RESOLVES (StatTask.submitTask looks
   # the id up in BuiltInRegistries.CUSTOM_STAT and walk_one_cm is there), but it
   # is the wrong task for this quest twice over: it observes nothing about
   # minimap config, and StatTask reads the LIFETIME counter, so it self-completes
   # the moment the chapter opens for anyone who has already walked 3km.
   [t_check("Disable one of the two minimaps")],
   [r_xp(80), r_skill(3)]),
  (6, 2, "Generate It Early",
   ["Terrain generating under you is what causes the stutter while sailing.",
    "Chunky builds it in advance.", "",
    "/chunky center 0 0 then /chunky radius 3000 then /chunky start.",
    "Track it with /chunky progress, stop it with /chunky pause -- it saves.", "",
    "It will saturate your CPU. Run it while you are not playing."],
   [t_check("Finish a Chunky pregeneration task")],
   [r_xp(100), r_skill(4)]),
  (8, 0, "Claim Your Ground",
   ["Open the Claim Manager (Controls -> FTB Chunks) and left-click chunks.", "",
    "A claimed chunk stops other players breaking blocks or opening containers",
    "inside it. Your team shares the claim; allies can be let in per team.", "",
    "You get a fixed number of claims. Spend them on the base, not the ocean."],
   [t_check("Claim a chunk in the Claim Manager")],
   [r_xp(80), r_skill(3)]),
  (8, -2, "Keep It Ticking",
   ["SHIFT-click a claimed chunk in the Claim Manager to force-load it.", "",
    "Force-loaded chunks keep ticking when nobody is nearby. Without this every",
    "generator, quarry and farm in this cluster freezes the moment you sail off.", "",
    "Force-load allowance is far smaller than claim allowance. Cover the",
    "machine room, not the whole island."],
   [t_check("Force-load a chunk")],
   [r_xp(100), r_skill(4)]),
  (10, 0, "Find Your Crew",
   ["Open your inventory and click the My Team button in the sidebar.",
    "Create a Party -- you cannot make one from a command in this pack.", "",
    "Party members share quest progress, chunk claims and quest rewards.",
    "Ally another team from the same screen to let them past your claims.", "",
    "Essential adds a friends list and invites on top, if you use it."],
   [t_check("Create or join a party")],
   [r_xp(80), r_skill(3)]),
  (12, 0, "Say Something",
   ["Simple Voice Chat is proximity audio. Bind Push to Talk under",
    "Options -> Controls -> Voice Chat, then open the Voice Chat Menu",
    "to choose your microphone and test the level.", "",
    "Whisper shortens your range. Groups let a crew talk across the whole",
    "map -- which is the only sane way to run a ship with someone up the mast."],
   [t_check("Talk to another player on voice chat")],
   [r_xp(60), r_skill(2)]),
  (14, 0, "See Past The Horizon",
   ["Distant Horizons renders low-detail terrain far beyond your render distance.",
    "On an ocean pack that is the difference between sailing blind and seeing land.", "",
    "Set VANILLA render distance low and DH's LOD distance high. That pairing",
    "is the whole point -- raising both just costs you the framerate twice.", "",
    "DH can only draw chunks that have been generated, so pregenerate first."],
   [t_check("Enable Distant Horizons and set a far LOD distance")],
   [r_xp(80), r_skill(3)]),
  (14, 2, "Turn On The Light",
   ["Iris loads shaders. The pack ships Complementary Reimagined in",
    "shaderpacks/, and Euphoria Patches is installed to extend it.", "",
    "Options -> Video Settings -> Shader Packs.", "",
    "If the framerate collapses, lower the shader's own profile before you",
    "touch render distance. Shaders cost far more than chunks do."],
   [t_check("Enable a shader pack")],
   [r_xp(60), r_skill(2)]),
  (16, 0, "When It Stutters",
   ["Sodium replaces the renderer, Lithium the server tick, ModernFix the load",
    "path, Entity Culling and ImmediatelyFast the draw calls. All already on.", "",
    "When it still stutters: F3 shows chunk updates and memory pressure.",
    "Sodium's own options are under Video Settings, and Reese's Sodium Options",
    "exposes sliders vanilla hides.", "",
    "Do not remove these to 'debug' a problem. They are not the problem."],
   [t_check("Open Sodium's video settings and check your frame time")],
   [r_xp(40), r_skill(2)]),
  (16, -2, "Packs You Never Enabled",
   ["Global Packs loads datapacks from globalpacks/datapacks/ into every world",
    "you make, so pack-wide loot and worldgen apply without per-save fiddling.", "",
    "BlazeandCave's Advancements Pack rides in this way.", "",
    "/datapack list will show them. If one is missing, that folder is where to look."],
   [t_check("Run /datapack list and find a global pack")],
   [r_xp(40), r_skill(2)]),
 ]),

 ("Wandcraft", "Build by the hundred", "wands:diamond_wand", [
  (0, 0, "A Wand Of Cobble",
   ["Cobblestone and two sticks. The Stone Wand extends what you click.", "",
    "Hold blocks in your offhand or inventory, click a block face, and the wand",
    "repeats that block along the face until it runs out of range or material.", "",
    "Deepslate cobble works too if that is what you have."],
   [t_item("wands:stone_wand")],
   [r_xp(60), r_skill(3)]),
  (2, 0, "Put A Tool In It",
   ["Copper Wand. Now open the Wand Menu (bind it in Controls -> Building Wands).", "",
    "Version 3 wands hold a TOOL. Drop a pickaxe, shovel or axe into the wand's",
    "tool slot -- without one, Destroy and Replace actions refuse to run and you",
    "get 'No tool -- add a tool to wand'. The tool takes the durability.", "",
    "The four Actions are Place, Replace, Destroy and Use."],
   [t_item("wands:copper_wand")],
   [r_xp(80), r_skill(3)]),
  (2, -2, "The Palette",
   ["An item frame and a chest. The Palette holds a set of blocks and feeds them",
    "to the wand instead of a single block type.", "",
    "Palette Mode cycles how it picks: Sequential walks the list in order,",
    "Random scatters, Gradient blends across the build.", "",
    "This is how you get mixed stone walls without placing anything by hand."],
   [t_item("wands:palette")],
   [r_xp(80), r_skill(3)]),
  (4, 0, "Iron Wand",
   ["More range, more blocks per swing. Now learn the modes.", "",
    "Mode key cycles: Direction, Row/Column, Line, Grid, Circle, Sphere, Box,",
    "Fill, Area, Vein, Copy, Paste, Rock, Blast.", "",
    "Line and Fill take two clicks -- first point, then second. Area floods",
    "across connected blocks of the same type. Undo has its own key; use it."],
   [t_item("wands:iron_wand")],
   [r_xp(100), r_skill(4)]),
  (4, 2, "Magic Bag",
   ["String, rabbit hide, purple dye and an ender pearl.", "",
    "A Magic Bag holds building stock and the wand pulls from it directly,",
    "so you are not carrying nine stacks of stone in your hotbar.", "",
    "Open it with the Magic Bag Menu key."],
   [t_item("wands:magic_bag_1")],
   [r_xp(80), r_skill(3)]),
  (6, 0, "Diamond Wand",
   ["The working wand. Range and block limit are high enough for real structures.", "",
    "Open Configuration for the settings that matter: Limit caps blocks per",
    "action, Reach extends how far you can click, Replace decides whether you",
    "only fill air, or also fluids and plants, or overwrite anything.", "",
    "Replace = all needs a tool in the wand, because it breaks what is there."],
   [t_item("wands:diamond_wand")],
   [r_xp(140), r_skill(5)]),
  (6, 2, "Bigger Bag",
   ["Tier 2 swaps the ender pearl for an Eye of Ender -- AND the purple dye",
    "for ORANGE. Reusing the tier 1 layout with purple will not craft.", "",
    "More slots. Pair it with the Palette -- bag holds the stock, palette",
    "decides the pattern."],
   [t_item("wands:magic_bag_2")],
   [r_xp(100), r_skill(3)]),
  (8, 0, "Netherite Wand",
   ["A smithing table job: Diamond Wand, netherite ingot, netherite upgrade template.", "",
    "Top range, top block limit. Copy and Paste modes become genuinely useful",
    "here -- select a region, copy it, and stamp it along a coastline.", "",
    "Pattern Rotate and Mirror flip the pasted copy without re-selecting it."],
   [t_item("wands:netherite_wand")],
   [r_xp(200), r_skill(6)]),
  (8, -2, "Bag Of Stars",
   ["Tier 3 costs a Nether Star, with MAGENTA dye in place of the orange.",
    "Largest capacity in the mod.", "",
    "Worth it only if you are building at Netherite Wand scale."],
   [t_item("wands:magic_bag_3")],
   [r_xp(200), r_skill(5)]),
 ]),

 ("Powah", "From coal and clay to a nether star", "powah:energizing_orb", [
  (0, 0, "Paste From Coal And Clay",
   ["Three coal, two clay balls and a lava bucket make 24 Dielectric Paste.",
    "Paste is the base of every single thing Powah builds.", "",
    "Powah runs on Forge Energy, which on Fabric is the same Team Reborn Energy",
    "that QuarryPlus consumes and Flux Networks moves. One grid, three mods."],
   [t_item("powah:dielectric_paste", 24)],
   [r_xp(60), r_skill(3)]),
  (0, -2, "The Manual And The Wrench",
   ["Paste plus a book gives you the Powah manual -- it has a page for every",
    "block, with the numbers. Read it instead of guessing at tiers.", "",
    "The Wrench has three modes, cycled by sneak-clicking: Rotate turns a block,",
    "Config edits cable and machine sides, Link re-pairs energizing rods to an orb."],
   [t_item("powah:book"), t_item("powah:wrench")],
   [r_xp(60), r_skill(2)]),
  (2, 0, "Rods And Casings",
   ["Paste plus iron bars gives Dielectric Rods, eight at a time. Two shapes:",
    "the plain rod and the Horizontal rod. Recipes want a specific one.", "",
    "Rod + horizontal rod + iron makes a Dielectric Casing: the chassis every",
    "generator, cell and cable is built around."],
   [t_item("powah:dielectric_casing", 4)],
   [r_xp(80), r_skill(3)]),
  (4, 0, "Capacitors",
   ["Iron, redstone block and paste make four Basic Capacitors.",
    "One capacitor splits into two Tiny Capacitors.", "",
    "Tiny is what almost every starter recipe asks for. Make a stack of them",
    "now -- you will burn through them for the rest of the chapter."],
   [t_item("powah:capacitor_basic_tiny", 8)],
   [r_xp(80), r_skill(3)]),
  (6, 0, "Burn Something",
   ["The Furnator burns ordinary furnace fuel -- coal, charcoal, planks.", "",
    "Higher tiers make more FE/t and hold more, but they also burn the fuel",
    "faster for the same total energy. Tiering up buys throughput, not efficiency.", "",
    "This is your first real generator. Put a Jade tooltip on it and watch it fill."],
   [t_item("powah:furnator_starter")],
   [r_xp(100), r_skill(4)]),
  (6, -2, "Lava Instead",
   ["The Magmator drinks hot fluids -- lava, straight from a bucket or piped in.", "",
    "Far more energy per unit than solid fuel. Pair it with the QuarryPlus",
    "Advanced Pump sitting over a lava lake and it feeds itself."],
   [t_item("powah:magmator_starter")],
   [r_xp(100), r_skill(3)]),
  (6, 2, "Free Watts",
   ["A Photoelectric Pane plus a casing makes a Solar Panel.", "",
    "It needs direct sky access. ANY block above it stops production dead --",
    "including a ship's rigging, which is the trap on this pack.", "",
    "Slow, but it never asks for fuel."],
   [t_item("powah:solar_panel_starter")],
   [r_xp(100), r_skill(3)]),
  (8, 0, "Cells And Cable",
   ["Energy Cables move power between machines. Sneak-click a cable with the",
    "Wrench in Config mode to change what a side does.", "",
    "The Energy Cell buffers it. Generators stall when the thing they feed is",
    "full; a cell in between keeps them running flat out.", "",
    "Cable tier caps transfer rate. A starter cable will throttle a nitro reactor."],
   [t_item("powah:energy_cell_starter"), t_item("powah:energy_cable_starter", 12)],
   [r_xp(120), r_skill(4)]),
  (10, 0, "The Orb",
   ["The Energizing Orb is Powah's crafting machine, and it is a multiblock",
    "of a sort: the orb itself uses NO energy. The rods do the work.", "",
    "Place the orb, then place Energizing Rods within range -- they link",
    "automatically. Each rod must sit on a cable or an energy block.", "",
    "Throw or right-click ingredients into the orb. More rods, and higher tier",
    "rods, mean faster crafts. One rod works; it is just slow."],
   [t_item("powah:energizing_orb"), t_item("powah:energizing_rod_starter", 4)],
   [r_xp(160), r_skill(5)]),
  (12, 0, "Energized Steel",
   ["Your first orb recipe: one iron and one gold ingot, 10,000 FE, two steel.", "",
    "Everything past this point is orb output. If the orb is slow, add rods",
    "or tier them up -- do not tier the orb, there is only one."],
   [t_item("powah:steel_energized", 8)],
   [r_xp(140), r_skill(4)]),
  (12, 2, "Heat Difference",
   ["The Thermo Generator sits ON TOP of a hot block or fluid -- lava -- and",
    "needs a coolant fluid, water, to run. Neither alone does anything.", "",
    "A Thermoelectric Plate is blaze powder, redstone and a tiny capacitor."],
   [t_item("powah:thermo_generator_starter")],
   [r_xp(120), r_skill(3)]),
  (14, 0, "Blazing And Niotic",
   ["Crystals are the tier ladder, and every one comes out of the orb.", "",
    "Four blaze powder at 120k FE gives a Blazing Crystal.",
    "One diamond at 300k FE gives a Niotic Crystal.", "",
    "Each machine tier is the previous tier's block plus that tier's crystal.",
    "You do not craft a Niotic Furnator from scratch; you upgrade one."],
   [t_item("powah:crystal_blazing", 4), t_item("powah:crystal_niotic", 4)],
   [r_xp(200), r_skill(6)]),
  (14, -2, "Charge Your Gear",
   ["A Battery charges anything chargeable while it sits in your inventory.", "",
    "The Energy Hopper does the same job for a chest: put it against an",
    "inventory and it tops up the charged items inside.", "",
    "Batteries also upgrade Ender Network channel capacity later -- keep them."],
   [t_item("powah:battery_starter"), t_item("powah:energy_hopper_starter")],
   [r_xp(140), r_skill(4)]),
  (16, 0, "Raw Uraninite",
   ["Uraninite ore generates in three grades: Poor below y64, normal below y20,",
    "Dense below y0. Iron pickaxe or better; Fortune multiplies the drop.", "",
    "Mining WITHOUT Silk Touch is the only source of Raw Uraninite -- two per",
    "ore, more with Fortune. It smelts into Uraninite, which is what the",
    "reactor block is actually built from.", "",
    "Energizing the ore block in the orb skips the raw stage and yields five",
    "Uraninite directly. Faster for the reactor, but it will not finish THIS",
    "quest, which wants the raw drop.", "",
    "This is exactly the job the Chunk Destroyer exists for."],
   [t_item("powah:uraninite_raw", 8)],
   [r_xp(160), r_skill(5)]),
  (18, 0, "The Reactor",
   ["A real multiblock. Hold THIRTY-SIX Reactor blocks and place them into a",
    "3x3x4 clear area -- the reactor assembles itself from your hand. The mod's",
    "own manual says '3X4'; it means 3 by 3, four tall. Reactor blocks craft",
    "four at a time, so that is nine crafts and 36 Uraninite.", "",
    "It burns Uraninite. Running heats it up, and a hot reactor eats more fuel",
    "for less output, so it needs water piped in as coolant. Snow or ice adds",
    "extra cooling, but only on top of a liquid coolant, never instead of it.", "",
    "Keep the fuel buffer full. A starved reactor produces almost nothing."],
   [t_item("powah:reactor_starter", 36)],
   [r_xp(300), r_skill(8)]),
  (18, 2, "Bound To You",
   ["The Player Transmitter charges everything in a linked player's inventory,",
    "armour and offhand included, anywhere in the same dimension.", "",
    "The transmitter is built around a PLAYER AERIAL PEARL, which has no recipe",
    "of any kind. Craft an ordinary Aerial Pearl -- paste, iron bars and an",
    "ender pearl -- then USE it on a Zombie or a Husk to convert it. Nothing in",
    "the crafting tree tells you this; REI files it on the item's info tab.", "",
    "RIGHT-CLICK a Binding Card to bind it to yourself FIRST, then put the card",
    "in the transmitter. An unbound card does nothing and gives no error.", "",
    "The Dimensional Binding Card lifts the same-dimension limit."],
   [t_item("powah:binding_card"), t_item("powah:player_transmitter_starter")],
   [r_xp(200), r_skill(5)]),
  (20, 0, "Spirited And Nitro",
   ["One emerald at 1,000,000 FE gives a Spirited Crystal.", "",
    "Nitro is the wall: a nether star, two redstone blocks and a Blazing Crystal",
    "block at 20,000,000 FE -- for sixteen crystals. Budget a night of reactor",
    "uptime and a rod array that is not starter tier.", "",
    "Nitro tier machines are the endgame of this mod."],
   [t_item("powah:crystal_spirited", 4), t_item("powah:crystal_nitro", 4)],
   [r_xp(400), r_skill(10)]),
  (22, 0, "The Ender Network",
   ["Ender Cells store energy to a numbered CHANNEL on your own ender network,",
    "readable from any other Ender Cell anywhere in the world.", "",
    "A fresh channel has no capacity. Shift-click an Energy Cell or a Battery",
    "into the Ender Cell GUI to donate its capacity -- and its charge -- to the",
    "channel. That step is the one everyone misses.", "",
    "Ender Gates push and pull between the network and an adjacent block, but",
    "cannot add capacity."],
   [t_item("powah:ender_cell_starter"), t_item("powah:ender_gate_starter")],
   [r_xp(300), r_skill(8)]),
 ]),

 ("The Quarry", "Strip mining, automated", "quarryplus:quarry", [
  (0, 0, "Flexible Markers",
   ["Glowstone, lapis and a redstone torch. Markers define where a machine digs.", "",
    "Place one and RIGHT-CLICK it to open its GUI: you type the area size in",
    "directly rather than dragging out a rectangle.", "",
    "Note: the plain Marker Plus has no recipe in this version. Flexible Markers",
    "and Chunk Markers are the two you actually build."],
   [t_item("quarryplus:flex_marker", 3)],
   [r_xp(80), r_skill(3)]),
  (2, 0, "Chunk Markers",
   ["Three Flexible Markers make one Chunk Marker.", "",
    "A Chunk Marker snaps its area to chunk boundaries, which is what you want",
    "for anything long-running -- a chunk-aligned dig is a chunk you can",
    "force-load exactly."],
   [t_item("quarryplus:marker16", 4)],
   [r_xp(100), r_skill(4)]),
  (2, -2, "Status Checker",
   ["Glass, iron and any marker.", "",
    "Right-click a machine with it to read its energy Requires and Receives",
    "figures and its installed enchantments. When a quarry sits there doing",
    "nothing, this is the tool that tells you it is simply underfed."],
   [t_item("quarryplus:status_checker")],
   [r_xp(60), r_skill(2)]),
  (2, 2, "Y Setter",
   ["Glass, lapis and any marker.", "",
    "Right-click a quarry with it to set the Y level it stops at. It answers",
    "'Quarry digs to <y>'.", "",
    "Without one the quarry goes to bedrock. Set a floor when you only want",
    "the deepslate layer and not the whole column."],
   [t_item("quarryplus:y_setter")],
   [r_xp(60), r_skill(2)]),
  (4, 0, "Quarry Plus",
   ["Two gold pickaxes, a dropper, a redstone block, iron and obsidian.", "",
    "Place the quarry TOUCHING a marker and the marker's area becomes the dig",
    "area. It builds a frame around the region, then strips everything inside",
    "down to bedrock and pushes the drops into whatever inventory it faces.", "",
    "It needs energy -- the same FE Powah makes. Feed it a cable, not a hope."],
   [t_item("quarryplus:quarry")],
   [r_xp(200), r_skill(6)]),
  (6, 0, "Enchant It First",
   ["QuarryPlus machines carry enchantments, and you apply them to the ITEM",
    "in an anvil BEFORE you place the block.", "",
    "Quarry and Chunk Destroyer take Efficiency, Unbreaking, Fortune and Silk",
    "Touch. Advanced Pump takes Efficiency, Unbreaking and Fortune.", "",
    "Efficiency is speed, Unbreaking cuts energy cost, and Fortune and Silk",
    "Touch do exactly what they do on a pickaxe. Silk Touch and Fortune",
    "conflict -- pick one."],
   [t_check("Place a quarry that has an enchantment on it")],
   [r_xp(160), r_skill(5)]),
  (6, -2, "Two Reasons It Stopped",
   ["'Area is too small' means the markers do not enclose enough space.", "",
    "'Area contains protected chunks. Quarry has stopped.' means the dig",
    "region overlaps an FTB Chunks claim that is not yours. A quarry will not",
    "eat another team's claim, and it will not warn you until it hits one.", "",
    "Chunk-align the markers and claim the whole dig before you start."],
   [t_check("Read a quarry's stop reason and fix its area")],
   [r_xp(100), r_skill(3)]),
  (8, 0, "Chunk Destroyer",
   ["A Quarry, four Chunk Markers, two emeralds and green dye.", "",
    "The Chunk Destroyer clears its whole marked region in one pass rather",
    "than head-by-head, and by default it VOIDS common material -- stone, dirt,",
    "gravel -- keeping only what is worth keeping.", "",
    "This is the machine that gets you uraninite and diamonds in bulk."],
   [t_item("quarryplus:adv_quarry")],
   [r_xp(300), r_skill(8)]),
  (8, -2, "Through Bedrock",
   ["Obsidian and two markers make a Remove Bedrock Module.", "",
    "You do not place it. Put the module and a Quarry or Chunk Destroyer",
    "together in a crafting grid to install it into that machine.", "",
    "The machine then mines bedrock. In the Nether that means the roof too."],
   [t_item("quarryplus:remove_bedrock_module")],
   [r_xp(200), r_skill(6)]),
  (10, 0, "Advanced Pump",
   ["A Quarry, two diamonds, buckets, markers and green dye.", "",
    "The Advanced Pump is standalone -- it does not attach to a quarry.",
    "Place it directly ABOVE a fluid block and it drains the body out.", "",
    "Its Delete toggle voids what it pulls instead of tanking it, which is how",
    "you dry out an ocean trench before digging it. Frame toggle stops it",
    "building the visible frame."],
   [t_item("quarryplus:adv_pump")],
   [r_xp(200), r_skill(6)]),
  (10, 2, "The Filler",
   ["Iron, a ladder and an iron axe. The Filler is the quarry run backwards.", "",
    "Give it a marker area and a stack of blocks and it fills the region,",
    "or just builds the frame, depending on mode.", "",
    "The fastest way to floor a hole a Chunk Destroyer just made."],
   [t_item("quarryplus:filler")],
   [r_xp(160), r_skill(5)]),
  (12, 0, "Placer Plus",
   ["A dispenser, gold, mossy cobble, redstone and iron.", "",
    "Placer Plus actually PLACES blocks from its inventory instead of shooting",
    "them out like a dispenser does.", "",
    "Right-click it with a redstone torch to change its redstone mode."],
   [t_item("quarryplus:placer_plus")],
   [r_xp(140), r_skill(4)]),
  (12, 2, "Remote Placer",
   ["Placer Plus, two diamonds, iron and two ender pearls.", "",
    "Same job at a distance -- it places into a remote position you configure",
    "rather than the block in front of its face."],
   [t_item("quarryplus:remote_placer")],
   [r_xp(160), r_skill(4)]),
  (14, 0, "Underwater Markers",
   ["A marker plus green dye gives its waterlogged twin.", "",
    "Ordinary markers break the water column when you place them, which floods",
    "your build site the moment you pull them. Waterlogged ones do not.", "",
    "On an ocean pack this is not optional."],
   [t_item("quarryplus:waterlogged_marker16")],
   [r_xp(120), r_skill(4)]),
 ]),

 ("Wire and Warehouse", "Flux Networks and Tom's Storage", "fluxnetworks:flux_controller", [
  (0, 0, "Flux Dust",
   ["Flux Dust has no crafting recipe. You make it in the world.", "",
    "Place OBSIDIAN directly on top of BEDROCK, drop Redstone Dust items onto",
    "the obsidian, then click the obsidian. The redstone converts and the",
    "obsidian is consumed.", "",
    "REI has a 'Creating Flux' page for it if the layout will not take."],
   [t_item("fluxnetworks:flux_dust", 8)],
   [r_xp(120), r_skill(4)]),
  (2, 0, "Flux Cores",
   ["Flux Dust, obsidian and an Eye of Ender make four Flux Cores.", "",
    "Cores are the base of every flux device. FOUR cores and FIVE dust,",
    "checkerboarded, give a Flux Block -- both a crafting component and the",
    "storage block's ingredient."],
   [t_item("fluxnetworks:flux_core", 8), t_item("fluxnetworks:flux_block")],
   [r_xp(140), r_skill(4)]),
  (4, 0, "Plug And Point",
   ["The whole mod is two blocks and they are easy to get backwards.", "",
    "A Flux PLUG goes on a generator and pushes power INTO the network.",
    "A Flux POINT goes on a machine and pulls power OUT of the network.", "",
    "Both attach to the face of the block they serve. No cable between them --",
    "the network is wireless, and it crosses dimensions."],
   [t_item("fluxnetworks:flux_plug"), t_item("fluxnetworks:flux_point")],
   [r_xp(180), r_skill(6)]),
  (4, -2, "The Configurator",
   ["Obsidian, flux dust and an Eye of Ender.", "",
    "Copies a device's network and transfer settings, then pastes them onto",
    "the next twenty. Once you are running a real grid you stop hand-editing",
    "each plug."],
   [t_item("fluxnetworks:flux_configurator")],
   [r_xp(100), r_skill(3)]),
  (6, 0, "The Controller",
   ["Flux cores, a Flux Block and flux dust.", "",
    "ONE Controller per network, and only one. It wirelessly charges items in",
    "the inventories of players inside its range, and it unlocks the network's",
    "full statistics and per-device transfer limits.", "",
    "Networks are created in any flux device's GUI. You get a small number",
    "of your own -- most people need exactly one."],
   [t_item("fluxnetworks:flux_controller")],
   [r_xp(240), r_skill(7)]),
  (6, 2, "Flux Storage",
   ["A Flux Block wrapped in glass panes.", "",
    "A Basic Flux Storage is a network-attached battery -- it does not need a",
    "plug or a point, it joins the network directly.", "",
    "Flux devices can also force-load their own chunk, which is the cheapest",
    "way to keep a remote generator alive."],
   [t_item("fluxnetworks:basic_flux_storage")],
   [r_xp(180), r_skill(5)]),
  (8, 0, "Gargantuan",
   ["Basic upgrades to Herculean, Herculean to Gargantuan, each by re-wrapping",
    "it in glass panes.", "",
    "These upgrades use a special recipe that KEEPS the energy already stored.",
    "You never have to drain a storage block before tiering it up."],
   [t_item("fluxnetworks:gargantuan_flux_storage")],
   [r_xp(300), r_skill(8)]),
  (10, 0, "The Connector",
   ["Planks, a chest, a comparator, a diamond and an ender pearl.", "",
    "Tom's Simple Storage has exactly one core block: the Inventory Connector.",
    "Every inventory TOUCHING it becomes part of one shared pool.", "",
    "It is a surface-area problem. Six faces is six chests -- everything else",
    "in this half of the chapter exists to get around that."],
   [t_item("toms_storage:ts.inventory_connector")],
   [r_xp(140), r_skill(5)]),
  (12, 0, "The Terminal",
   ["Planks, chest, comparator, glass and glowstone.", "",
    "The Storage Terminal is the window into the pool. It must touch the",
    "connector, or reach it through cable.", "",
    "Type in the search box, sort with the buttons in the corner. Shift-click",
    "pulls a stack out the way it does everywhere else."],
   [t_item("toms_storage:ts.storage_terminal")],
   [r_xp(160), r_skill(5)]),
  (12, -2, "Trim The Edges",
   ["Planks, sticks and a chest, two at a time.", "",
    "Inventory Trim extends the connector's reachable surface. Chests touching",
    "a trim block count as touching the connector.", "",
    "This is how a six-chest wall becomes a sixty-chest wall."],
   [t_item("toms_storage:ts.trim", 8)],
   [r_xp(120), r_skill(4)]),
  (14, 0, "Craft From The Grid",
   ["A Storage Terminal, a crafting table and a diamond.", "",
    "The Crafting Terminal is the Storage Terminal with a 3x3 attached that",
    "pulls ingredients straight out of the pool.", "",
    "Click a recipe in REI while it is open and it will fill the grid for you."],
   [t_item("toms_storage:ts.crafting_terminal")],
   [r_xp(200), r_skill(6)]),
  (14, 2, "Cable It Out",
   ["Inventory Cable is planks, sticks, a trapdoor and a chest -- six a craft.", "",
    "Cable alone carries nothing. It needs an Inventory Cable Connector at each",
    "end: one on the storage connector, one on the remote chest or terminal.", "",
    "The Filtered connector adds an item filter to that link, so you can send",
    "only cobblestone down one run."],
   [t_item("toms_storage:ts.inventory_cable", 6),
    t_item("toms_storage:ts.inventory_cable_connector")],
   [r_xp(200), r_skill(6)]),
  (16, 0, "Filters",
   ["Wool, redstone and a stick make a basic Item Filter.", "",
    "Add a comparator and a name tag for the Tag filter -- it matches an entire",
    "item tag, so #logs catches every wood at once.", "",
    "Add a comparator and a diamond for the Polymorphic filter, which matches",
    "items similar to the one you set rather than exactly it."],
   [t_item("toms_storage:ts.item_filter"),
    t_item("toms_storage:ts.tag_item_filter")],
   [r_xp(160), r_skill(5)]),
  (16, -2, "Level Emitter",
   ["Planks, cable, a comparator and a redstone torch.", "",
    "Set an item and a count; it emits redstone when the pool crosses that",
    "threshold. That is your 'keep 2000 cobble, then shut the quarry off' wire."],
   [t_item("toms_storage:ts.level_emitter")],
   [r_xp(160), r_skill(5)]),
  (16, 2, "Crate And Proxy",
   ["The Open Crate drops whatever is pushed into it onto the ground -- or into",
    "whatever is below it. Void unwanted quarry output with one.", "",
    "The Inventory Proxy makes the block behind it look like part of the",
    "network from a face it is not touching, and can filter what shows through."],
   [t_item("toms_storage:ts.open_crate"),
    t_item("toms_storage:ts.inventory_proxy")],
   [r_xp(140), r_skill(4)]),
  (18, 0, "Wireless Terminal",
   ["Planks, a comparator, glass, glowstone, an ender pearl and a spyglass.",
    "No chest, unlike every other terminal in this chapter.", "",
    "SNEAK-RIGHT-CLICK a Storage Terminal with it to bind it to that terminal.",
    "An unbound wireless terminal opens nothing.", "",
    "Limited range from the bound terminal."],
   [t_item("toms_storage:ts.wireless_terminal")],
   [r_xp(240), r_skill(7)]),
  (20, 0, "Netherite Wireless",
   ["Smithing table: Wireless Terminal, netherite upgrade template, netherite ingot.", "",
    "Longer range and it works across dimensions. The last thing this mod",
    "asks you for, and the point at which your storage stops being a room",
    "you have to walk to."],
   [t_item("toms_storage:ts.adv_wireless_terminal")],
   [r_xp(400), r_skill(10)]),
 ]),
